#cloud-config
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC++7VKa2plZdIB1IrdnTW69QQPReY3AKzzmMJU8AwlQ9J3GteaCiLBU/6nUfw7XycvKaGRxtOHuZCqDAbEc0aVAIXHTPRcpCcIGFwCSF2l5gpbPsIo6qAOgd9UaVBrdKD4SKAcsa8mmtWJO6bOzQLTU/kVn24/fW6LHqAbabciYCTCpr09HBSMWXwcI8ZJuAOil1LFoKd73JELCEupUPDMxpcrFEdcJvy9wjumnuBmknEt2zfv0yBHd1zc9xHviyNmyunn49Ap/b6DzT1I8fLJ4eeWexKuGtw9aPGcWrzKrHy/0z3/3Kr78wUHZD6y5AaotVpI8ov8dYjpZ53xFYPj felipe@md1rfbec
rancher:
  preload_wait: true
  resize_device: /dev/sda
  network:
    dns:
      nameservers:
        - 8.8.8.8
        - 8.8.4.4
  services:
    guacd:
      image: guacamole/guacd:latest
      restart: always
      labels:
        io.rancher.os.scope: "system"
    abacate:
      image: crochik/abacate:latest
      restart: always  
      ports:
        - 8080:8080
      labels:
        io.rancher.os.scope: "system"      
    portainer:
      image: portainer/portainer
      ports:
        - 9000:9000
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      labels:
        io.rancher.os.scope: "system"      
hostname: felipeos
