#cloud-config
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC++7VKa2plZdIB1IrdnTW69QQPReY3AKzzmMJU8AwlQ9J3GteaCiLBU/6nUfw7XycvKaGRxtOHuZCqDAbEc0aVAIXHTPRcpCcIGFwCSF2l5gpbPsIo6qAOgd9UaVBrdKD4SKAcsa8mmtWJO6bOzQLTU/kVn24/fW6LHqAbabciYCTCpr09HBSMWXwcI8ZJuAOil1LFoKd73JELCEupUPDMxpcrFEdcJvy9wjumnuBmknEt2zfv0yBHd1zc9xHviyNmyunn49Ap/b6DzT1I8fLJ4eeWexKuGtw9aPGcWrzKrHy/0z3/3Kr78wUHZD6y5AaotVpI8ov8dYjpZ53xFYPj felipe@md1rfbec
rancher:
  resize_device: /dev/sda
  docker:
    # https://rancher.com/docs/os/v1.x/en/installation/configuration/docker/
    # tls: true
    # tls_args:
    #   - "--tlsverify"
    #   - "--tlscacert=/etc/docker/tls/ca.pem"
    #   - "--tlscert=/etc/docker/tls/server-cert.pem"
    #   - "--tlskey=/etc/docker/tls/server-key.pem"
    #   - "-H=0.0.0.0:2376"    
  network:
    dns:
      nameservers:
        - 8.8.8.8
        - 8.8.4.4
write_files:
  - path: /home/rancher/test.txt
    owner: rancher
    content: |
      this is getting fun
  - path: /etc/rc.local
    permissions: "0755"
    owner: root
    content: |
      #!/bin/bash
      wait-for-docker
      docker run -d nginx      
runcmd:
  - [ touch, /home/rancher/test2.txt ]
  - echo "test2" > /home/rancher/test3.txt
hostname: felipeos
